/** Catálogo canónico de acciones de auditoría (cliente + docs). */
export const AUDIT_ACTIONS = {
  LOGIN: 'login',
  LOGOUT: 'logout',
  LOGIN_FAILED: 'login.failed',
  USER_CREATE: 'user.create',
  USER_UPDATE: 'user.update',
  USER_DELETE: 'user.delete',
  USER_PROFILE: 'user.profile_update',
  DEVICE_VIEW_LIST: 'device.view_list',
  DEVICE_VIEW_DETAIL: 'device.view_detail',
  TELEMETRY_VIEW_3H: 'telemetry.view',
  DOWNLOAD_EQUIPO_JSON: 'download.equipo_json',
  DOWNLOAD_HISTORIAL_CSV: 'download.historial_csv',
  DOWNLOAD_HISTORIAL_XLSX: 'download.historial_xlsx',
  DOWNLOAD_HISTORIAL_PDF: 'download.historial_pdf',
  DOWNLOAD_HISTORIAL_JSON: 'download.historial_json',
  DEVICE_NAME_UPDATE: 'device.name_update',
  EMPRESA_CREATE: 'empresa.create',
  EMPRESA_UPDATE: 'empresa.update',
  EMPRESA_DELETE: 'empresa.delete',
  EMPRESA_ASSIGN: 'empresa.assign',
  CORREO_SMTP: 'correo.smtp_update',
  CORREO_GRUPO: 'correo.grupo_change',
  ALARMA_CONFIG: 'alarma.config_update',
  DASHBOARD_REVIEW: 'dashboard.device_review',
  CONTROL_COMMAND: 'control.command',
  INCIDENTE_ATENDER: 'incidente.atender',
  INCIDENTE_COMENTAR: 'incidente.comentar',
  INCIDENTE_ARCHIVE: 'incidente.archive',
  CORREO_HISTORIAL_LIMPIAR: 'correo.historial_limpiar',
} as const;

export const AUDIT_MODULES = [
  'auth',
  'usuarios',
  'perfil',
  'listado',
  'empresas',
  'correo',
  'alarma',
  'dashboard',
  'control',
  'analisis',
  'app',
] as const;
