import type { HistorialFieldDef } from './types';

/** Catálogo normativo (manejo_tabla_grafica.md). USDA alineado a −40…50. */
export const HISTORIAL_FIELD_CATALOG: HistorialFieldDef[] = [
  {
    key: 'temp_supply_1',
    label: 'Suministro',
    chartable: true,
    tableable: true,
    axis: 'temp',
    min: -45,
    max: 50,
    unit: '°C',
    color: '#1B5E20',
    conTendencia: true,
  },
  {
    key: 'temp_supply_2',
    label: 'Suministro 2',
    chartable: true,
    tableable: true,
    axis: 'temp',
    min: -45,
    max: 50,
    unit: '°C',
    color: '#43A047',
  },
  {
    key: 'return_air',
    label: 'Retorno',
    chartable: true,
    tableable: true,
    axis: 'temp',
    min: -45,
    max: 50,
    unit: '°C',
    color: '#E53935',
    conTendencia: true,
  },
  {
    key: 'evaporation_coil',
    label: 'Evaporador',
    chartable: true,
    tableable: true,
    axis: 'temp',
    min: -45,
    max: 50,
    unit: '°C',
    color: '#9E9E9E',
  },
  {
    key: 'condensation_coil',
    label: 'Condensador',
    chartable: true,
    tableable: true,
    axis: 'temp',
    min: -45,
    max: 99,
    unit: '°C',
    color: '#FF7043',
  },
  {
    key: 'compress_coil_1',
    label: 'Compresor',
    chartable: true,
    tableable: true,
    axis: 'temp',
    min: -45,
    max: 120,
    unit: '°C',
    color: '#8D6E63',
  },
  {
    key: 'ambient_air',
    label: 'Exterior',
    chartable: true,
    tableable: true,
    axis: 'temp',
    min: -45,
    max: 50,
    unit: '°C',
    color: '#66BB6A',
  },
  {
    key: 'cargo_1_temp',
    label: 'USDA 1',
    chartable: true,
    tableable: true,
    axis: 'temp',
    min: -40,
    max: 50,
    unit: '°C',
    color: '#0288D1',
  },
  {
    key: 'cargo_2_temp',
    label: 'USDA 2',
    chartable: true,
    tableable: true,
    axis: 'temp',
    min: -40,
    max: 50,
    unit: '°C',
    color: '#00897B',
  },
  {
    key: 'cargo_3_temp',
    label: 'USDA 3',
    chartable: true,
    tableable: true,
    axis: 'temp',
    min: -40,
    max: 50,
    unit: '°C',
    color: '#F57C00',
  },
  {
    key: 'cargo_4_temp',
    label: 'USDA 4',
    chartable: true,
    tableable: true,
    axis: 'temp',
    min: -40,
    max: 50,
    unit: '°C',
    color: '#5E35B1',
  },
  {
    key: 'relative_humidity',
    label: 'Humedad',
    chartable: true,
    tableable: true,
    axis: 'pct',
    min: 20,
    max: 99,
    unit: '%',
    color: '#AB47BC',
  },
  {
    key: 'avl',
    label: 'AVL',
    chartable: false,
    tableable: true,
    axis: null,
    min: 0,
    max: 250,
    unit: 'cfm',
  },
  {
    key: 'line_voltage',
    label: 'Voltaje',
    chartable: false,
    tableable: true,
    axis: null,
    min: 0,
    max: 500,
    unit: 'V',
  },
  {
    key: 'line_frequency',
    label: 'Frecuencia',
    chartable: false,
    tableable: true,
    axis: null,
    min: 0,
    max: 90,
    unit: 'Hz',
  },
  {
    key: 'consumption_ph_1',
    label: 'Fase 1',
    chartable: false,
    tableable: true,
    axis: null,
    min: 0,
    max: 19.9,
    unit: 'A',
  },
  {
    key: 'consumption_ph_2',
    label: 'Fase 2',
    chartable: false,
    tableable: true,
    axis: null,
    min: 0,
    max: 19.9,
    unit: 'A',
  },
  {
    key: 'consumption_ph_3',
    label: 'Fase 3',
    chartable: false,
    tableable: true,
    axis: null,
    min: 0,
    max: 19.9,
    unit: 'A',
  },
  {
    key: 'co2_reading',
    label: 'CO2',
    chartable: true,
    tableable: true,
    axis: 'pct',
    min: 0,
    max: 24.9,
    unit: '%',
    color: '#26A69A',
  },
  {
    key: 'o2_reading',
    label: 'O2',
    chartable: true,
    tableable: true,
    axis: 'pct',
    min: 0,
    max: 24.9,
    unit: '%',
    color: '#29B6F6',
  },
  {
    key: 'evaporator_speed',
    label: 'Ventilación Evaporador',
    chartable: false,
    tableable: true,
    axis: null,
    min: 0,
    max: 99,
  },
  {
    key: 'condenser_speed',
    label: 'Ventilación Condensador',
    chartable: false,
    tableable: true,
    axis: null,
    min: 0,
    max: 99,
  },
  {
    key: 'battery_voltage',
    label: 'V Batería',
    chartable: false,
    tableable: true,
    axis: null,
    min: 0,
    max: 12,
    unit: 'V',
    transform: 'battery_div10',
  },
  {
    key: 'power_kwh',
    label: 'Contador Eléctrico',
    chartable: false,
    tableable: true,
    axis: null,
    min: 0.1,
    max: Number.POSITIVE_INFINITY,
    unit: 'kWh',
    transform: 'power_kwh_min',
  },
  {
    key: 'supply_air_temp',
    label: 'Sensor Aire Suministro',
    chartable: false,
    tableable: true,
    axis: null,
    min: -40,
    max: 50,
    unit: '°C',
  },
  {
    key: 'return_air_temp',
    label: 'Sensor Aire Retorno',
    chartable: false,
    tableable: true,
    axis: null,
    min: -40,
    max: 50,
    unit: '°C',
  },
  {
    key: 'dl_battery_temp',
    label: 'Temperatura Batería',
    chartable: false,
    tableable: true,
    axis: null,
    min: -40,
    max: 120,
    unit: '°C',
  },
  {
    key: 'power_consumption',
    label: 'Consumo',
    chartable: false,
    tableable: true,
    axis: null,
    min: 0.1,
    max: 20,
    unit: 'kWh',
  },
  {
    key: 'power_consumption_avg',
    label: 'Consumo Promedio',
    chartable: false,
    tableable: true,
    axis: null,
    min: 0.1,
    max: 20,
    unit: 'kWh',
  },
  {
    key: 'alarm_present',
    label: 'Alarmas Presentes',
    chartable: false,
    tableable: true,
    axis: null,
    min: 0,
    max: 9,
  },
  {
    key: 'set_point',
    label: 'Set Temperatura',
    chartable: true,
    tableable: true,
    axis: 'temp',
    min: -40,
    max: 50,
    unit: '°C',
    color: '#FDD835',
    strokeWidth: 2.5,
  },
  {
    key: 'capacity_load',
    label: 'Potencia Compresor',
    chartable: true,
    tableable: true,
    axis: 'pct',
    min: 0,
    max: 100,
    unit: '%',
    color: '#EC407A',
  },
  {
    key: 'power_state',
    label: 'Power',
    chartable: false,
    tableable: true,
    axis: null,
    min: 0,
    max: 1,
    transform: 'power_state_override',
  },
  {
    key: 'controlling_mode',
    label: 'Modo Control',
    chartable: false,
    tableable: true,
    axis: null,
    min: 0,
    max: 9,
  },
  {
    key: 'humidity_control',
    label: 'Control Humedad',
    chartable: false,
    tableable: true,
    axis: null,
    min: 0,
    max: 9,
  },
  {
    key: 'humidity_set_point',
    label: 'Set Humedad',
    chartable: true,
    tableable: true,
    axis: 'pct',
    min: 20,
    max: 99,
    unit: '%',
    color: '#CE93D8',
  },
  {
    key: 'fresh_air_ex_mode',
    label: 'Control Ventilación',
    chartable: false,
    tableable: true,
    axis: null,
    min: 0,
    max: 9,
  },
  {
    key: 'set_point_o2',
    label: 'Set O2',
    chartable: true,
    tableable: true,
    axis: 'pct',
    min: 0,
    max: 24.9,
    unit: '%',
    color: '#4FC3F7',
  },
  {
    key: 'set_point_co2',
    label: 'Set CO2',
    chartable: true,
    tableable: true,
    axis: 'pct',
    min: 0,
    max: 24.9,
    unit: '%',
    color: '#80CBC4',
  },
  {
    key: 'defrost_term_temp',
    label: 'Temporizador Defrost',
    chartable: false,
    tableable: true,
    axis: null,
    min: 0,
    max: 24,
  },
  {
    key: 'defrost_interval',
    label: 'Intervalo Defrost',
    chartable: false,
    tableable: true,
    axis: null,
    min: 0,
    max: 24,
  },
  {
    key: 'sp_ethyleno',
    label: 'SP Etileno',
    chartable: true,
    tableable: true,
    axis: 'high',
    min: 0,
    max: 300,
    unit: 'ppm',
    color: '#FFA726',
  },
  {
    key: 'inyeccion_hora',
    label: 'Horas Inyección',
    chartable: false,
    tableable: true,
    axis: null,
    min: 0,
    max: 120,
  },
  {
    key: 'ethylene',
    label: 'Etileno',
    chartable: true,
    tableable: true,
    axis: 'high',
    min: 0,
    max: 300,
    unit: 'ppm',
    color: '#EF6C00',
  },
  {
    key: 'numero_alarma',
    label: 'Alarmas',
    chartable: false,
    tableable: true,
    axis: null,
    min: 0,
    max: 9,
  },
  {
    key: 'alarma_01',
    label: 'Alarma 1',
    chartable: false,
    tableable: true,
    axis: null,
    min: 0,
    max: 200,
  },
  {
    key: 'alarma_02',
    label: 'Alarma 2',
    chartable: false,
    tableable: true,
    axis: null,
    min: 0,
    max: 200,
  },
];

const BY_KEY = new Map(HISTORIAL_FIELD_CATALOG.map((f) => [f.key, f]));

export function getHistorialFieldDef(key: string): HistorialFieldDef | undefined {
  return BY_KEY.get(key);
}

export function chartableFields(): HistorialFieldDef[] {
  return HISTORIAL_FIELD_CATALOG.filter((f) => f.chartable);
}

export function tableableFields(): HistorialFieldDef[] {
  return HISTORIAL_FIELD_CATALOG.filter((f) => f.tableable);
}
